In [2]:
import torch

### Manipulating tensors (tensor operation)

1. Addition
2. Sub
3. Mul (element wise)
4. Div 
5. Matrix Multiplication

In [3]:
tensor  = torch.tensor([1,2,3])
tensor = tensor+10
tensor

tensor([11, 12, 13])

In [4]:
tensor = tensor*10
tensor

tensor([110, 120, 130])

In [5]:
tensor = tensor/10
tensor

tensor([11., 12., 13.])

In [6]:
tensor = tensor - 10
tensor

tensor([1., 2., 3.])

In [7]:
torch.mul(tensor,10)


tensor([10., 20., 30.])

## Matrix Multiplication

In [8]:
torch.matmul(tensor,tensor)

tensor(14.)

In [9]:
t1 = torch.tensor([1,2,3,4,])

#torch.matmul(t1,tensor)
t1 = t1.type(torch.float32)

torch.matmul(t1,tensor)

# Size gives error

RuntimeError: inconsistent tensor size, expected tensor [4] and src [3] to have the same number of elements, but got 4 and 3 elements respectively

In [22]:
%%time 
value = 0
for i in range(len(tensor)):
    value+=(tensor[i]*tensor[i])
print(value)

tensor(14.)
CPU times: total: 46.9 ms
Wall time: 16.2 ms


In [25]:
%%time
torch.matmul(tensor,tensor)

## Takes very less time

CPU times: total: 0 ns
Wall time: 59.6 μs


tensor(14.)

### One of the most common errors in Deep Learning : Shape Errors

In [10]:
#Tensor1

tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### We can resolve this issue using transpose

In [11]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [13]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])