In [1]:
import torch

### Manipulating tensors (tensor operation)

1. Addition
2. Sub
3. Mul (element wise)
4. Div 
5. Matrix Multiplication

In [7]:
tensor  = torch.tensor([1,2,3])
tensor = tensor+10
tensor

tensor([11, 12, 13])

In [8]:
tensor = tensor*10
tensor

tensor([110, 120, 130])

In [9]:
tensor = tensor/10
tensor

tensor([11., 12., 13.])

In [11]:
tensor = tensor - 10
tensor

tensor([1., 2., 3.])

In [12]:
torch.mul(tensor,10)


tensor([10., 20., 30.])

## Matrix Multiplication

In [13]:
torch.matmul(tensor,tensor)

tensor(14.)

In [21]:
t1 = torch.tensor([1,2,3,4,])

#torch.matmul(t1,tensor)
t1 = t1.type(torch.float32)

torch.matmul(t1,tensor)

# Size gives error

RuntimeError: inconsistent tensor size, expected tensor [4] and src [3] to have the same number of elements, but got 4 and 3 elements respectively

In [22]:
%%time 
value = 0
for i in range(len(tensor)):
    value+=(tensor[i]*tensor[i])
print(value)

tensor(14.)
CPU times: total: 46.9 ms
Wall time: 16.2 ms


In [25]:
%%time
torch.matmul(tensor,tensor)

## Takes very less time

CPU times: total: 0 ns
Wall time: 59.6 μs


tensor(14.)