In [2]:
import torch
import numpy as np

## Pytorch tensors with Numpy

1. Data in Numpy to Pytorch Tensor ->   `torch.from_numpy(ndarray)`
2. Pytorch tensor to Numpy -> `torch.Tensor.numpy()`

In [6]:
array = np.arange(1,10)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [8]:
array.dtype , tensor.dtype

(dtype('int64'), torch.int64)

In [15]:
t1 = torch.ones(5)
np_t1 = t1.numpy()
np_t1, t1

(array([1., 1., 1., 1., 1.], dtype=float32), tensor([1., 1., 1., 1., 1.]))

## Reproducibility (trying to take out the random out of the random)

Neural Networks learn :

1. start with random numbers
2. tensor operations
3. update random numbers
4. make them better representation of data (again and again)


that's why we use random seed


In [17]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
r1 = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
r2 = torch.rand(3,4)
print(r1)
print(r2)
print(r1 == r2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [18]:
!nvidia-smi

Thu May 22 16:00:32 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.02                 Driver Version: 576.02         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8              3W /   60W |     359MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [19]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'