In [2]:
import torch

In [13]:
print(torch.__version__)

2.7.0+cu128


In [14]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

Pytorch tensors are created using torch.tensor()

In [16]:
scalar.ndim
#dimension of tensor

0

In [17]:
#get tensor back as python number
scalar.item()


7

In [22]:
#vector
vector = torch.tensor([7, 7])
vector 
#dimension of tensor
vector.ndim

vector.shape



torch.Size([2])

In [24]:
#Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
#dimension of tensor
print(MATRIX.ndim)

MATRIX.shape



tensor([[ 7,  8],
        [ 9, 10]])
2


torch.Size([2, 2])

In [25]:
# Tensor 
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(TENSOR)
#dimension of tensor
print(TENSOR.ndim)

TENSOR.shape



tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3


torch.Size([1, 3, 3])

In [48]:
# Random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8047, 0.2479, 0.2277, 0.4820],
        [0.2875, 0.0928, 0.5092, 0.1835],
        [0.9094, 0.0557, 0.1548, 0.4479]])

# Why random tensors? 

random tensors are imp because the way many neural networkds learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [38]:
random_tensor.size()

torch.Size([3, 4])

In [49]:
random_tensor.shape
random_tensor.ndim


2

In [67]:
r1  = torch.rand(10,10,10)
r1 = r1.to("cuda")
r1.device

device(type='cuda', index=0)

In [68]:
random_image_size_tensor = torch.rand(size=(3,256,256))
random_image_size_tensor.ndim , random_image_size_tensor.shape

(3, torch.Size([3, 256, 256]))