In [1]:
import torch

### Zeroes and ones

In [3]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
one.dtype

torch.float32

In [8]:
zero.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [11]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
steppers = torch.arange(start = 0, end = 1000, step = 100)
steppers

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [16]:
#Like method

ten_zeroes = torch.zeros_like(input = steppers)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

*Note* : Tensor datatypes is one of the 3 big erros you'll run into with Pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [18]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_tensor = torch.tensor([3,6,9], dtype = None #what is datatype of this tensor?
                            , device = 'cuda' #what is device of this tensor?
                            , requires_grad=False #do you need to record operations on this tensor?
                            )
float_tensor.device


device(type='cuda', index=0)

In [24]:
float_16_tensor  = float_32_tensor.type(torch.float16)
float_16_tensor ,  float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [26]:
float_16_tensor*float_32_tensor

#Sometimes it may throw an error and sometimes it may not

tensor([ 9., 36., 81.], dtype=torch.float16)

In [27]:
int_32_tensor = float_32_tensor.type(torch.int32)


In [28]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting info from tensors (tensor attributes):

1. Tensors not right datatype - tensor.dtype
2. Tensors not right shape - tensor.shape
3. Tensors not on the right device - tensor.device