In [2]:
import torch

### Finding the min , max , sum of tensors (tensor aggregation)

In [3]:
x = torch.arange(0,100,10)

In [4]:
torch.min(x), x.min() , x.max()

(tensor(0), tensor(0), tensor(90))

In [5]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [6]:
x = x.type(torch.float32)

In [7]:
x.mean()

tensor(45.)

In [8]:
t1 = torch.tensor([[1,2],[3,4],[5,6]])
t1.sum()
t1.type(torch.float32).mean()

tensor(3.5000)

In [9]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [10]:
x.argmin() ##Finds the position of the minimum value


tensor(0)

## Reshaping , Stacking , Squeezing and Unsqueezing a tensor

1. Reshape - reshapes an input tensor to a defined shape
2. View - returns the view of an input tensor at a certain shape but keeps the same memory as the original tensor
3. Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Squeezing - removes all `1` dimensions from a tensor
5. Unsqueeze - add a `1` dimension to a target tensor
6. Permute - return a view with dimensions of the tensor permuted in a certain way 

In [11]:
a = torch.arange(1,10)
a,a.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [12]:
## Add an extra dimension

a.reshape(3,3)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
## Change the view

z = a.view([1,9])
z.shape , z

(torch.Size([1, 9]), tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]))

#### Changing z changes a , as the view of a tensor shares the same memory as the original input

In [15]:
z,a

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [16]:
z[:,0] = 5
z, a

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [17]:
## Stack tensors on top of each other

a_stack = torch.stack([a,a,a,a], dim  = 1)
a_stack

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [26]:
t1 = torch.tensor([[[0,0],[4,4],[8,8]],[[1,2],[3,4],[5,6]]])
print(t1.shape)
t1 = torch.stack([t1,t1])
t1, t1.shape

torch.Size([2, 3, 2])


(tensor([[[[0, 0],
           [4, 4],
           [8, 8]],
 
          [[1, 2],
           [3, 4],
           [5, 6]]],
 
 
         [[[0, 0],
           [4, 4],
           [8, 8]],
 
          [[1, 2],
           [3, 4],
           [5, 6]]]]),
 torch.Size([2, 2, 3, 2]))

In [37]:
# torch.squeeze

t2 = torch.zeros([2,1,2,2,1])
t2.shape , t2

(torch.Size([2, 1, 2, 2, 1]),
 tensor([[[[[0.],
            [0.]],
 
           [[0.],
            [0.]]]],
 
 
 
         [[[[0.],
            [0.]],
 
           [[0.],
            [0.]]]]]))

In [38]:
t3 = torch.squeeze(t2)
t3.shape , t3

(torch.Size([2, 2, 2]),
 tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [47]:
## Torch.permute

t4 = torch.rand([2,4,3])
t4.shape

torch.Size([2, 4, 3])

In [51]:
torch.permute(t4, (2,0,1)).shape

torch.Size([3, 2, 4])

### Indexing

In [54]:
t6 = torch.arange(1,10).reshape(1,3,3)

In [55]:
t6.shape

torch.Size([1, 3, 3])

In [58]:
t6[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
t6[0,2]

tensor([7, 8, 9])

In [68]:
t6[0,1,2]

tensor(6)